server.port=8761
spring.application.name=discovery

# Ne pas s'enregistrer lui-meme comme client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Interface web Eureka
eureka.server.wait-time-in-ms-when-sync-empty=0
